daemon off;
error_log /dev/stderr info;

events { }

http {
    access_log /dev/stdout;

    server {
        listen 67;

        # A four-digit status code — the whole point of this fork.
        location / { return 6767 "Ok\n"; }
    }
}
